apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
     app: nginx
     teir: deployement

spec:
  replicas: 3
  selector:
    matchLabels:
        app: nginx
        teir: deployement
  template:
    metadata:
      labels:
        app: nginx
        teir: deployement
    spec:
      containers:
      - name: nginx1
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    teir: deployment
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port