apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
     app: nginx
     teir: frontend

spec:
  replicas: 3
  selector:
    matchLabels:
        app: nginx
        teir: frontend
  template:
    metadata:
      labels:
        app: nginx
        teir: frontend
    spec:
      containers:
      - name: nginx1
        image: nginx:mainline-alpine3.18-perl
        

