apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
   name: mouli
spec:
  containers:
  - name: env-demo
    image: nginx
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: demo_ping
      value: "hello ping pong"
