apiVersion: v1
kind: Pod
metadata:
  name: hellopod
spec:
 containers:
   - name: hellopod
     image: nginx
     ports:
     - containerport: 80
     resources:
      requests:
        cpu: "100m"
        memory: "68mi"
      limits:
        cpu: "200m"
        memory: "128mi"


