apiVersion: v1
kind: Pod
metadata:
   name: config-map
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
    - name: student
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: student
---
apiVersion: v1
kind: Pod
metadata:
   name: config-map1
spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
          name: devops-config
        


